### ISSUE TITLE
User specified image doesn't work

### ISSUE THREAD

**Issue by pezholio** [exaviorn/RasPiWrite#3]
Hi,

I've successfully used RasPiWrite to download and write an image to an SD card, but it seems that when trying to write a user-specified image, the path of the image file is repeated. Here's the out put after I try 'accept':

`Running dd bs=1m if=/Users/stuart/Downloads/RasPiWrite/OpenELEC.10977.img.gz//Users/stuart/Downloads/RasPiWrite/OpenELEC.10977.img.gz of=/dev/disk1...Waiting
dd: /Users/stuart/Downloads/RasPiWrite/OpenELEC.10977.img.gz//Users/stuart/Downloads/RasPiWrite/OpenELEC.10977.img.gz: Not a directory`

I'd try and fix it myself, but my Python skills are somewhat lacking!

**Comment by radiomarko** [comment]
The script seems to only want to download an older image not the latest so I similarly tried to point the script to my download of it, resulting in:

Do you wish to Download a Raspberry Pi compatible image (choose yes if you don't have one) (Y/n): n
Please locate the disk image (.zip, .img.gz, .tar.bz2 (.tar.bz2 only working with QtonPi distros currently): /Users/eMac/Documents/Raspberry\ Pi/debian6-04-2012.zip
Traceback (most recent call last):
  File "raspiwrite.py", line 424, in <module>
    driveTest(SD) #action gets delegated to driveTest, which then leads on to the next step, I found this to be the easiest way
  File "raspiwrite.py", line 370, in driveTest
    getImage(SD)
  File "raspiwrite.py", line 343, in getImage
    if matchGzip is not None:
UnboundLocalError: local variable 'matchGzip' referenced before assignment
imac intel_001b63b88fdc:exaviorn-RasPiWrite-62f0517 eMac$ 

Beyond me! Help please.

**Comment by exaviorn** [comment]
Hi, make sure that the debian.zip file is in the same directory as Raspiwrite.py, then simply type 'debian6-04-2012.zip' at when you are asked to locate the image.

Sorry about the late reply, I'm afraid I lost the email among the large amounts of comment emails I've received on the exaviorn blog post for RasPiWrite

**Comment by srcshelton** [comment]
Same issue here:

```
Do you wish to Download a Raspberry Pi compatible image (choose yes if you don't have one) (Y/n): n
Please locate the disk image (.zip, .img.gz, .tar.bz2 (.tar.bz2 only working with QtonPi distros currently): /Users/Stuart/Downloads/debian6-19-04-2012.zip
Found Zip
Found archive inputted by user, extracting...
Ok... Unzipping the disk , this may take a while...
Archive:  /Users/Stuart/Downloads/debian6-19-04-2012.zip
   creating: debian6-19-04-2012/
  inflating: debian6-19-04-2012/debian6-19-04-2012.img.sha1  
  inflating: debian6-19-04-2012/debian6-19-04-2012.img  
/Users/Stuart/Downloads/debian6-19-04-2012/debian6-19-04-2012.img

...

Please verify this information before typing 'accept' to accept the terms and to start the process, if this information isn't correct, please press ctrl + c (^C), or type 'exit' to quit: accept
Running dd bs=1m if=/Users/Stuart/Downloads/debian6-19-04-2012/debian6-19-04-2012.img of=/dev/disk2...
Waitingdd: /Users/Stuart/Downloads/debian6-19-04-2012/debian6-19-04-2012.img: No such file or directory
done!
.Transfer Complete! Please remove the SD card
```

... the result of running 'dd' should probably be checked to see whether the transfer was successful...
