### ISSUE TITLE
ExpatError: not well-formed, in checkforUpdate()

### ISSUE THREAD

**Issue by mrluc** [exaviorn/RasPiWrite#66]
Even after applying the indentation and syntax fixes others have contributed, I get this:

```
//////////////////////// 
* Raspberry Pi SD Writer 
* Matt Jump
* exaviorn.com
////////////////////////
(Version 1.15 -MACOSX-)

Checking for updates...
Traceback (most recent call last):
  File "./raspiwrite.py", line 440, in <module>
    checkforUpdate()
  File "./raspiwrite.py", line 68, in checkforUpdate
    dom = parseString(data)
  File     "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1924, in parseString
    return expatbuilder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 14, column 59
```

**Comment by GilDev** [comment]
Same error since some days.

**Comment by msarvar** [comment]
http://exaviorn.com/ seems to be down. It's trying to pull raspiwrite.xml from there. 
As a temporary solution, try commenting checkforUpdate() out in line 436.

**Comment by nanook62** [comment]
In my script it's line 440 that should be commenting. Now it works perfect.
